### ISSUE TITLE
Using End Portal costs hunger

### ISSUE THREAD

**Issue by onewithtehforce** [VladoCC/get_back_home#1]
as per title, using the end portal from the end back to the overworld applies a hunger cost
since the /home or /back command is not used it should not

v1.5 of the mod in the v4.5a Dungeons Dragons and Space Shuttles pack

**Comment by VladoCC** [comment]
Are you dev of this modpack or just player?

**Comment by onewithtehforce** [comment]
I'm playing the pack not developing it

**Comment by VladoCC** [comment]
I'm 100% sure that it isn't problem with my mod.
Give me steps to reproduce ir video, where you can show this bug in game without other mods.
My mod don't have any interaction with mods other than AppleCore, so if bug can't be reproduced without other mods - it isn't bug of my mod.

**Comment by VladoCC** [comment]
close
