### ISSUE TITLE
Mistagged versions on CurseForge

### ISSUE THREAD

**Issue by shedaniel** [VladoCC/get_back_home#4]
![image](https://user-images.githubusercontent.com/34910653/53948364-9d852700-4102-11e9-985f-1b49637ca1da.png)
1.14 and 1.13 is tagged for whatever reason

**Comment by VladoCC** [comment]
It is tagged with this version because when Forge and AppleCore will be released fir this versions, my mod will work without any changes.
It was discussed so many time, that I think to add it as first paragraph in mod description and in bold.
